// AUTO-GENERATED by `pnpm gen:types` (scripts/gen-types.mjs) — do not edit by hand.
// Source of truth: the migrations in supabase/migrations/.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      alert_locations: {
        Row: {
          alert_id: string
          id: string
          lat: number
          lng: number
          recorded_at: string
        }
        Insert: {
          alert_id: string
          id?: string
          lat: number
          lng: number
          recorded_at?: string
        }
        Update: {
          alert_id?: string
          id?: string
          lat?: number
          lng?: number
          recorded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "alert_locations_alert_id_fkey"
            columns: ["alert_id"]
            isOneToOne: false
            referencedRelation: "alerts"
            referencedColumns: ["id"]
          },
        ]
      }
      alerts: {
        Row: {
          created_at: string
          id: string
          last_lat: number | null
          last_lng: number | null
          resolved_at: string | null
          status: Database["public"]["Enums"]["alert_status"]
          trigger_type: Database["public"]["Enums"]["alert_trigger_type"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          last_lat?: number | null
          last_lng?: number | null
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["alert_status"]
          trigger_type?: Database["public"]["Enums"]["alert_trigger_type"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          last_lat?: number | null
          last_lng?: number | null
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["alert_status"]
          trigger_type?: Database["public"]["Enums"]["alert_trigger_type"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "alerts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      emergency_contacts: {
        Row: {
          created_at: string
          id: string
          name: string
          phone: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          phone: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          phone?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "emergency_contacts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      guardian_links: {
        Row: {
          accepted_at: string | null
          created_at: string
          guardian_id: string | null
          id: string
          invite_code: string
          status: Database["public"]["Enums"]["guardian_link_status"]
          user_id: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          guardian_id?: string | null
          id?: string
          invite_code?: string
          status?: Database["public"]["Enums"]["guardian_link_status"]
          user_id: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          guardian_id?: string | null
          id?: string
          invite_code?: string
          status?: Database["public"]["Enums"]["guardian_link_status"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "guardian_links_guardian_id_fkey"
            columns: ["guardian_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "guardian_links_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      journeys: {
        Row: {
          created_at: string
          destination_note: string | null
          expected_arrival_at: string
          grace_period_minutes: number
          id: string
          last_lat: number | null
          last_lng: number | null
          notified_at: string | null
          resolved_at: string | null
          status: Database["public"]["Enums"]["journey_status"]
          user_id: string
        }
        Insert: {
          created_at?: string
          destination_note?: string | null
          expected_arrival_at: string
          grace_period_minutes?: number
          id?: string
          last_lat?: number | null
          last_lng?: number | null
          notified_at?: string | null
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["journey_status"]
          user_id: string
        }
        Update: {
          created_at?: string
          destination_note?: string | null
          expected_arrival_at?: string
          grace_period_minutes?: number
          id?: string
          last_lat?: number | null
          last_lng?: number | null
          notified_at?: string | null
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["journey_status"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "journeys_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          fake_call_caller_name: string | null
          fake_call_enabled: boolean
          full_name: string
          id: string
          phone: string | null
          preferred_language: Database["public"]["Enums"]["preferred_language"]
          role: Database["public"]["Enums"]["profile_role"]
          shake_sos_enabled: boolean
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          fake_call_caller_name?: string | null
          fake_call_enabled?: boolean
          full_name: string
          id: string
          phone?: string | null
          preferred_language?: Database["public"]["Enums"]["preferred_language"]
          role: Database["public"]["Enums"]["profile_role"]
          shake_sos_enabled?: boolean
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          fake_call_caller_name?: string | null
          fake_call_enabled?: boolean
          full_name?: string
          id?: string
          phone?: string | null
          preferred_language?: Database["public"]["Enums"]["preferred_language"]
          role?: Database["public"]["Enums"]["profile_role"]
          shake_sos_enabled?: boolean
        }
        Relationships: []
      }
      push_tokens: {
        Row: {
          created_at: string
          expo_push_token: string
          id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          expo_push_token: string
          id?: string
          user_id: string
        }
        Update: {
          created_at?: string
          expo_push_token?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      check_overdue_journeys: { Args: never; Returns: undefined }
      generate_invite_code: { Args: never; Returns: string }
      normalize_phone: { Args: { p_phone: string }; Returns: string }
      redeem_guardian_invite: { Args: { p_invite_code: string }; Returns: Json }
      resolve_login_identifier: {
        Args: { identifier: string }
        Returns: string
      }
    }
    Enums: {
      alert_status: "active" | "resolved" | "false_alarm"
      alert_trigger_type: "manual" | "journey_overdue"
      guardian_link_status: "pending" | "accepted" | "revoked"
      journey_status:
        | "active"
        | "arrived_safe"
        | "alert_triggered"
        | "cancelled"
      preferred_language: "bn" | "en"
      profile_role: "user" | "guardian"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      alert_status: ["active", "resolved", "false_alarm"],
      alert_trigger_type: ["manual", "journey_overdue"],
      guardian_link_status: ["pending", "accepted", "revoked"],
      journey_status: [
        "active",
        "arrived_safe",
        "alert_triggered",
        "cancelled",
      ],
      preferred_language: ["bn", "en"],
      profile_role: ["user", "guardian"],
    },
  },
} as const

// Convenience aliases — the shapes consumed by mobile/ and dashboard/.
// Kept stable across regeneration so app code never has to reach into
// Database['public']['Tables'][...]['Row'] directly.
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Alert = Database['public']['Tables']['alerts']['Row'];
export type GuardianLink = Database['public']['Tables']['guardian_links']['Row'];
export type EmergencyContact = Database['public']['Tables']['emergency_contacts']['Row'];
