import * as Clipboard from 'expo-clipboard';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, RefreshControl, Share, View } from 'react-native';

import Avatar from '@/components/Avatar';
import Banner from '@/components/ui/Banner';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import Screen from '@/components/ui/Screen';
import SegmentedControl from '@/components/ui/SegmentedControl';
import Text from '@/components/ui/Text';
import { useAuth } from '@/lib/auth-context';
import { formatInviteCode, revokeGuardianLink } from '@/lib/guardian-links';
import { useLanguage } from '@/lib/language-context';
import {
  DEFAULT_RETENTION_HOURS,
  RETENTION_PRESETS_HOURS,
  retentionLabelKey,
} from '@/lib/location-history-retention';
import { supabase } from '@/lib/supabase';
import { useTheme } from '@/theme';

type GuardianLinkRow = {
  id: string;
  status: 'pending' | 'accepted' | 'revoked';
  invite_code: string;
  created_at: string;
  guardian_id: string | null;
  guardian: { full_name: string; avatar_url: string | null } | null;
};

// retention_hours per guardian_id, for the "how long each guardian keeps
// my recorded location history" control shown under accepted links. Either
// party can change this (see location_history_retention RLS); a guardian
// changing it shows up here on the student's next refresh.
type RetentionRow = { guardian_id: string; retention_hours: number };

export default function GuardiansScreen() {
  const { session } = useAuth();
  const { t } = useLanguage();
  const { spacing } = useTheme();
  const router = useRouter();
  const userId = session?.user.id;

  const [links, setLinks] = useState<GuardianLinkRow[]>([]);
  const [retentionByGuardian, setRetentionByGuardian] = useState<Record<string, number>>({});
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [inviting, setInviting] = useState(false);
  const [cancellingId, setCancellingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [newCode, setNewCode] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const fetchLinks = useCallback(async () => {
    if (!userId) return;

    // Revoked links are history only; nothing on this screen needs them.
    const { data, error: linksError } = await supabase
      .from('guardian_links')
      .select(
        'id, status, invite_code, created_at, guardian_id, guardian:profiles!guardian_links_guardian_id_fkey(full_name, avatar_url)'
      )
      .eq('user_id', userId)
      .in('status', ['pending', 'accepted'])
      .order('created_at', { ascending: false });

    if (linksError) {
      setError(linksError.message);
      return;
    }
    setError(null);
    setLinks((data ?? []) as GuardianLinkRow[]);

    const { data: retention } = await supabase
      .from('location_history_retention')
      .select('guardian_id, retention_hours')
      .eq('user_id', userId)
      .eq('recorded_by_role', 'user');
    setRetentionByGuardian(
      Object.fromEntries(
        ((retention ?? []) as RetentionRow[]).map((r) => [r.guardian_id, r.retention_hours])
      )
    );
  }, [userId]);

  // Refetch on focus so the list is current after removing a guardian on
  // the confirmation screen.
  useFocusEffect(
    useCallback(() => {
      let active = true;
      fetchLinks().finally(() => {
        if (active) setLoading(false);
      });
      return () => {
        active = false;
      };
    }, [fetchLinks])
  );

  const setRetention = async (guardianId: string, hours: number) => {
    if (!userId) return;
    // Optimistic, same fire-and-forget pattern the settings toggles use.
    setRetentionByGuardian((prev) => ({ ...prev, [guardianId]: hours }));
    await supabase.from('location_history_retention').upsert(
      {
        user_id: userId,
        guardian_id: guardianId,
        retention_hours: hours,
        recorded_by_role: 'user',
      },
      { onConflict: 'user_id,guardian_id,recorded_by_role' }
    );
  };

  const handleRefresh = async () => {
    setRefreshing(true);
    await fetchLinks();
    setRefreshing(false);
  };

  const handleInvite = async () => {
    if (!userId) return;
    setError(null);
    setInviting(true);

    // invite_code is generated by the column default — don't set it here.
    const { data, error: insertError } = await supabase
      .from('guardian_links')
      .insert({ user_id: userId, status: 'pending' })
      .select('invite_code')
      .single();

    setInviting(false);

    if (insertError) {
      setError(insertError.message);
      return;
    }

    setNewCode(data.invite_code);
    setCopied(false);
    await fetchLinks();
  };

  const handleCancelCode = async (link: GuardianLinkRow) => {
    setCancellingId(link.id);
    const ok = await revokeGuardianLink(link.id);
    setCancellingId(null);
    if (!ok) {
      setError(t('guardianUpdateFailed'));
      return;
    }
    if (link.invite_code === newCode) setNewCode(null);
    await fetchLinks();
  };

  const handleCopy = async () => {
    if (!newCode) return;
    await Clipboard.setStringAsync(newCode);
    setCopied(true);
  };

  const handleShare = async () => {
    if (!newCode) return;
    await Share.share({ message: t('shareInviteMessage', { code: newCode }) });
  };

  const guardians = links.filter((link) => link.status === 'accepted');
  const unusedCodes = links.filter(
    (link) => link.status === 'pending' && link.invite_code !== newCode
  );

  return (
    <Screen
      edges={[]}
      contentStyle={{ gap: spacing.xl }}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
    >
      {error && <Banner tone="danger" message={error} />}

      {newCode ? (
        <Card>
          <View style={{ gap: spacing.md }}>
            <Text variant="label" color="textSecondary">
              {t('inviteCodeTitle')}
            </Text>
            <Text
              variant="display"
              script="latin"
              selectable
              accessibilityLabel={newCode.split('').join(' ')}
            >
              {formatInviteCode(newCode)}
            </Text>
            <Text variant="bodySm" color="textSecondary">
              {t('inviteCodeHint')}
            </Text>
            <View style={{ flexDirection: 'row', gap: spacing.sm }}>
              <View style={{ flex: 1 }}>
                <Button
                  title={t('shareCodeButton')}
                  variant="primary"
                  icon={{ ios: 'square.and.arrow.up', android: 'share', web: 'share' }}
                  onPress={handleShare}
                />
              </View>
              <Button
                title={copied ? t('copiedButton') : t('copyButton')}
                variant="secondary"
                fullWidth={false}
                onPress={handleCopy}
              />
            </View>
          </View>
        </Card>
      ) : (
        <Button
          title={t('inviteGuardianButton')}
          icon={{ ios: 'person.badge.plus', android: 'person_add', web: 'person_add' }}
          loading={inviting}
          loadingTitle={t('inviteGuardianButton')}
          onPress={handleInvite}
        />
      )}

      {newCode && (
        <Card variant="muted">
          <View style={{ gap: spacing.xs }}>
            <Text variant="label">{t('howItWorksTitle')}</Text>
            <Text variant="bodySm" color="textSecondary">
              {t('howItWorksBody')}
            </Text>
          </View>
        </Card>
      )}

      {unusedCodes.length > 0 && (
        <View style={{ gap: spacing.sm }}>
          <Text variant="label" color="textSecondary">
            {t('unusedCodesLabel')}
          </Text>
          {unusedCodes.map((link) => (
            <Card key={link.id} padding="md">
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}>
                <View style={{ flex: 1 }}>
                  <Text variant="title" script="latin">
                    {formatInviteCode(link.invite_code)}
                  </Text>
                  <Text variant="caption" color="textMuted">
                    {t('unusedCodeMeta', {
                      date: new Date(link.created_at).toLocaleDateString(),
                    })}
                  </Text>
                </View>
                <Button
                  title={t('cancelCodeButton')}
                  accessibilityLabel={t('cancelCodeLabel', { code: link.invite_code })}
                  variant="dangerOutline"
                  size="small"
                  fullWidth={false}
                  loading={cancellingId === link.id}
                  onPress={() => handleCancelCode(link)}
                />
              </View>
            </Card>
          ))}
        </View>
      )}

      <View style={{ gap: spacing.sm }}>
        <Text variant="label" color="textSecondary">
          {t('yourGuardiansCount', { n: guardians.length })}
        </Text>
        {loading && <ActivityIndicator />}
        {!loading && guardians.length === 0 && (
          <Text color="textSecondary">{t('noGuardiansYet')}</Text>
        )}
        {guardians.map((link) => {
          const guardianId = link.guardian_id;
          if (!guardianId) return null;
          const name = link.guardian?.full_name || t('unnamedGuardian');
          const retentionHours = retentionByGuardian[guardianId] ?? DEFAULT_RETENTION_HOURS;
          return (
            <Card key={link.id} padding="md">
              <View style={{ gap: spacing.md }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}>
                  <Avatar name={name} url={link.guardian?.avatar_url ?? null} size={44} />
                  <View style={{ flex: 1 }}>
                    <Text variant="title">{name}</Text>
                    <Text variant="caption" color="textMuted">
                      {t('guardianLinkedMeta')}
                    </Text>
                  </View>
                  <Button
                    title={t('removeGuardianButton')}
                    accessibilityLabel={t('removeGuardianLabel', { name })}
                    variant="secondary"
                    size="small"
                    fullWidth={false}
                    onPress={() =>
                      router.push({ pathname: '/remove-guardian', params: { linkId: link.id } })
                    }
                  />
                </View>
                {/* How long this guardian keeps my recorded location
                    history. Either party can change it (see
                    location_history_retention RLS). */}
                <View style={{ gap: spacing.xs }}>
                  <Text variant="caption" color="textSecondary">
                    {t('locationHistoryRetentionLabel')}
                  </Text>
                  <SegmentedControl
                    accessibilityLabel={t('locationHistoryRetentionLabel')}
                    value={String(retentionHours)}
                    onChange={(value) => setRetention(guardianId, Number(value))}
                    options={RETENTION_PRESETS_HOURS.map((hours) => ({
                      value: String(hours),
                      label: t(retentionLabelKey(hours)),
                    }))}
                  />
                </View>
              </View>
            </Card>
          );
        })}
      </View>

      {guardians.length > 0 && (
        <Button
          title={t('guardianLocationLink')}
          variant="ghost"
          onPress={() => router.push('/guardian-location')}
        />
      )}
    </Screen>
  );
}
