import * as Clipboard from 'expo-clipboard';
import { useCallback, useEffect, useState } from 'react';
import {
  ActivityIndicator,
  FlatList,
  Pressable,
  RefreshControl,
  Share,
  StyleSheet,
  Text,
  View,
} from 'react-native';

import Avatar from '@/components/Avatar';
import { useAuth } from '@/lib/auth-context';
import { useLanguage } from '@/lib/language-context';
import { supabase } from '@/lib/supabase';
import type { TranslationKey } from '@/lib/translations';

// This tab currently only covers guardians. Emergency contact management
// (a separate feature) lands here in a later step.

type GuardianLinkRow = {
  id: string;
  status: 'pending' | 'accepted' | 'revoked';
  invite_code: string;
  created_at: string;
  accepted_at: string | null;
  guardian: { full_name: string; avatar_url: string | null } | null;
};

export default function GuardiansScreen() {
  const { session } = useAuth();
  const { t } = useLanguage();
  const userId = session?.user.id;

  const [links, setLinks] = useState<GuardianLinkRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [inviting, setInviting] = useState(false);
  const [listError, setListError] = useState<string | null>(null);
  const [inviteError, setInviteError] = useState<string | null>(null);
  const [newInviteCode, setNewInviteCode] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const fetchLinks = useCallback(async () => {
    if (!userId) return;

    const { data, error } = await supabase
      .from('guardian_links')
      .select(
        'id, status, invite_code, created_at, accepted_at, guardian:profiles!guardian_links_guardian_id_fkey(full_name, avatar_url)'
      )
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) {
      setListError(error.message);
      return;
    }
    setListError(null);
    setLinks((data ?? []) as GuardianLinkRow[]);
  }, [userId]);

  useEffect(() => {
    // react-hooks/set-state-in-effect (the React Compiler-era strict rule)
    // flags any setState reachable from an effect, including this
    // fetch-on-mount-then-stop-loading pattern — there's no data-fetching
    // library in this project (React Query/SWR) to hand this off to, and
    // that's a bigger call than this step should make. This is the standard
    // fetch-on-mount pattern React's own docs used for years; disabling
    // deliberately rather than fighting the rule with indirection.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchLinks().finally(() => setLoading(false));
  }, [fetchLinks]);

  const handleRefresh = async () => {
    setRefreshing(true);
    await fetchLinks();
    setRefreshing(false);
  };

  const handleInvite = async () => {
    if (!userId) return;
    setInviteError(null);
    setInviting(true);

    // invite_code is generated by the column default — don't set it here.
    const { data, error } = await supabase
      .from('guardian_links')
      .insert({ user_id: userId, status: 'pending' })
      .select('invite_code')
      .single();

    setInviting(false);

    if (error) {
      setInviteError(error.message);
      return;
    }

    setNewInviteCode(data.invite_code);
    setCopied(false);
    await fetchLinks();
  };

  const handleCopy = async () => {
    if (!newInviteCode) return;
    await Clipboard.setStringAsync(newInviteCode);
    setCopied(true);
  };

  const handleShare = async () => {
    if (!newInviteCode) return;
    await Share.share({
      message: t('shareInviteMessage', { code: newInviteCode }),
    });
  };

  return (
    <View style={styles.container}>
      <FlatList
        data={links}
        keyExtractor={(item) => item.id}
        contentContainerStyle={styles.listContent}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} />}
        ListHeaderComponent={
          <View>
            <Text style={styles.title}>{t('guardiansTitle')}</Text>

            <Pressable
              style={[styles.button, inviting && styles.buttonDisabled]}
              onPress={handleInvite}
              disabled={inviting}
            >
              {inviting ? (
                <ActivityIndicator color="#fff" />
              ) : (
                <Text style={styles.buttonText}>{t('inviteGuardianButton')}</Text>
              )}
            </Pressable>

            {inviteError && <Text style={styles.error}>{inviteError}</Text>}

            {newInviteCode && (
              <View style={styles.inviteCard}>
                <Text style={styles.inviteCardLabel}>{t('shareCodeLabel')}</Text>
                <Pressable onPress={handleCopy}>
                  <Text style={styles.inviteCode}>{newInviteCode}</Text>
                </Pressable>
                <View style={styles.inviteCardActions}>
                  <Pressable style={styles.smallButton} onPress={handleCopy}>
                    <Text style={styles.smallButtonText}>
                      {copied ? t('copiedButton') : t('copyButton')}
                    </Text>
                  </Pressable>
                  <Pressable style={styles.smallButton} onPress={handleShare}>
                    <Text style={styles.smallButtonText}>{t('shareButton')}</Text>
                  </Pressable>
                </View>
              </View>
            )}

            {listError && <Text style={styles.error}>{listError}</Text>}

            <Text style={styles.sectionLabel}>{t('yourGuardiansLabel')}</Text>

            {loading && <ActivityIndicator style={styles.loadingIndicator} />}
            {!loading && links.length === 0 && (
              <Text style={styles.subtitle}>{t('noGuardiansYet')}</Text>
            )}
          </View>
        }
        renderItem={({ item }) => (
          <View style={styles.linkRow}>
            {item.status === 'accepted' && (
              <Avatar
                name={item.guardian?.full_name ?? null}
                url={item.guardian?.avatar_url ?? null}
                size={40}
              />
            )}
            <View style={styles.linkRowText}>
              <Text style={styles.linkName}>
                {item.status === 'accepted' && item.guardian
                  ? item.guardian.full_name || t('unnamedGuardian')
                  : item.invite_code}
              </Text>
              <Text style={styles.linkMeta}>
                {item.status === 'accepted'
                  ? t('acceptedOn', {
                      date: item.accepted_at ? new Date(item.accepted_at).toLocaleDateString() : '',
                    })
                  : t('createdOn', { date: new Date(item.created_at).toLocaleDateString() })}
              </Text>
            </View>
            <StatusBadge status={item.status} />
          </View>
        )}
      />
    </View>
  );
}

function StatusBadge({ status }: { status: GuardianLinkRow['status'] }) {
  const { t } = useLanguage();
  const statusKey: TranslationKey =
    status === 'accepted'
      ? 'statusAccepted'
      : status === 'revoked'
        ? 'statusRevoked'
        : 'statusPending';
  const style =
    status === 'accepted'
      ? styles.badgeAccepted
      : status === 'revoked'
        ? styles.badgeRevoked
        : styles.badgePending;
  return (
    <View style={[styles.badge, style]}>
      <Text style={styles.badgeText}>{t(statusKey)}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  listContent: {
    padding: 20,
    gap: 12,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    marginTop: 8,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    marginTop: 20,
    marginBottom: 8,
  },
  button: {
    backgroundColor: '#2f95dc',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  error: {
    color: '#d33',
    fontSize: 14,
    marginTop: 8,
  },
  loadingIndicator: {
    marginTop: 12,
  },
  inviteCard: {
    marginTop: 16,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#eef6fc',
    alignItems: 'center',
  },
  inviteCardLabel: {
    fontSize: 13,
    color: '#555',
    marginBottom: 8,
  },
  inviteCode: {
    fontSize: 32,
    fontWeight: 'bold',
    letterSpacing: 4,
    color: '#2f95dc',
  },
  inviteCardActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  smallButton: {
    backgroundColor: '#2f95dc',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  smallButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#f5f5f5',
  },
  linkRowText: {
    flex: 1,
  },
  linkName: {
    fontSize: 16,
    fontWeight: '600',
  },
  linkMeta: {
    fontSize: 12,
    color: '#888',
    marginTop: 2,
  },
  badge: {
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
    textTransform: 'capitalize',
  },
  badgePending: {
    backgroundColor: '#e0a800',
  },
  badgeAccepted: {
    backgroundColor: '#1a7f37',
  },
  badgeRevoked: {
    backgroundColor: '#888',
  },
});
