#!/usr/bin/env node
// Regenerates packages/shared-types/src/database.ts from the real Supabase
// schema, via `supabase gen types typescript`. The output keeps the same
// shape as the hand-written placeholder it replaces (a `Database` type plus
// Profile/Alert/GuardianLink/EmergencyContact aliases), so mobile/ and
// dashboard/ never need code changes when this is re-run.
//
// Usage:
//   pnpm gen:types                          # against the local `supabase start` stack
//   SUPABASE_PROJECT_ID=xxxx pnpm gen:types  # against a linked/remote project
//   pnpm gen:types --linked                  # against the project linked via `supabase link`
//
// Requires the Supabase CLI, invoked via `npx supabase` so no global install
// is needed (see the root package.json devDependency pin).

import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const outFile = path.join(repoRoot, 'packages/shared-types/src/database.ts');

const args = process.argv.slice(2);
const projectId = process.env.SUPABASE_PROJECT_ID;

let sourceFlags;
if (args.includes('--linked')) {
  sourceFlags = ['--linked'];
} else if (projectId) {
  sourceFlags = ['--project-id', projectId];
} else {
  sourceFlags = ['--local'];
}

console.log(`Running: supabase gen types typescript ${sourceFlags.join(' ')} --schema public`);

const result = spawnSync(
  'npx',
  ['--yes', 'supabase', 'gen', 'types', 'typescript', ...sourceFlags, '--schema', 'public'],
  { cwd: repoRoot, encoding: 'utf8', shell: true }
);

if (result.status !== 0) {
  console.error(result.stderr || result.stdout);
  console.error(
    '\nFailed to generate types. If you meant to run against your local stack, ' +
      'start it first with `pnpm exec supabase start`. To target a remote project instead, ' +
      'set SUPABASE_PROJECT_ID or run `pnpm gen:types -- --linked` after `supabase link`.'
  );
  process.exit(result.status ?? 1);
}

const generated = result.stdout.trimEnd();

const header = `// AUTO-GENERATED by \`pnpm gen:types\` (scripts/gen-types.mjs) — do not edit by hand.
// Source of truth: the migrations in supabase/migrations/.
`;

const aliases = `
// Convenience aliases — the shapes consumed by mobile/ and dashboard/.
// Kept stable across regeneration so app code never has to reach into
// Database['public']['Tables'][...]['Row'] directly.
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Alert = Database['public']['Tables']['alerts']['Row'];
export type GuardianLink = Database['public']['Tables']['guardian_links']['Row'];
export type EmergencyContact = Database['public']['Tables']['emergency_contacts']['Row'];
`;

fs.writeFileSync(outFile, `${header}\n${generated}\n${aliases}`);

console.log(`Wrote ${path.relative(repoRoot, outFile)}`);
