import * as Clipboard from 'expo-clipboard';
import { useState } from 'react';
import { Share, View } from 'react-native';

import Banner from '@/components/ui/Banner';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import Text from '@/components/ui/Text';
import { useAuth } from '@/lib/auth-context';
import { revokeGuardianLink } from '@/lib/guardian-links';
import { formatInviteCode, inviteCodeExpiresAt } from '@/lib/invite-code';
import { useLanguage } from '@/lib/language-context';
import { supabase } from '@/lib/supabase';
import { useTheme } from '@/theme';

export type PendingCode = { id: string; invite_code: string; created_at: string };

type Props = {
  // The student's unused old-style codes, newest first.
  pendingCodes: PendingCode[];
  onChanged: () => Promise<void>;
};

// A guardian still on 1.1/1.2 can't create a code, so the student makes an
// old-style one here and the guardian enters it in Link to Someone; they
// are linked as soon as they enter it. Removed with the old flow (see
// docs/plans/guardian-invite-requests.md, "Older apps").
export default function OlderAppGuardianInvite({ pendingCodes, onChanged }: Props) {
  const { session } = useAuth();
  const { t } = useLanguage();
  const { spacing } = useTheme();
  const userId = session?.user.id;

  const [open, setOpen] = useState(false);
  const [creating, setCreating] = useState(false);
  const [cancellingId, setCancellingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [newCode, setNewCode] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Codes made earlier stay visible without having to open the section.
  if (!open && pendingCodes.length === 0) {
    return (
      <Button title={t('olderAppGuardianToggle')} variant="ghost" onPress={() => setOpen(true)} />
    );
  }

  const handleCreate = async () => {
    if (!userId) return;
    setError(null);
    setCreating(true);
    // invite_code is generated by the column default — don't set it here.
    const { data, error: insertError } = await supabase
      .from('guardian_links')
      .insert({ user_id: userId, status: 'pending' })
      .select('invite_code')
      .single();
    setCreating(false);
    if (insertError) {
      setError(t('guardianUpdateFailed'));
      return;
    }
    setNewCode(data.invite_code);
    setCopied(false);
    await onChanged();
  };

  const handleCancel = async (code: PendingCode) => {
    setCancellingId(code.id);
    const ok = await revokeGuardianLink(code.id);
    setCancellingId(null);
    if (!ok) {
      setError(t('guardianUpdateFailed'));
      return;
    }
    if (code.invite_code === newCode) setNewCode(null);
    await onChanged();
  };

  const handleCopy = async () => {
    if (!newCode) return;
    await Clipboard.setStringAsync(newCode);
    setCopied(true);
  };

  const handleShare = async () => {
    if (!newCode) return;
    await Share.share({ message: t('shareInviteMessage', { code: newCode }) });
  };

  const unusedCodes = pendingCodes.filter((code) => code.invite_code !== newCode);

  return (
    <Card variant="muted">
      <View style={{ gap: spacing.md }}>
        <Text variant="label">{t('olderAppGuardianToggle')}</Text>
        <Text variant="bodySm" color="textSecondary">
          {t('olderAppGuardianHint')}
        </Text>

        {error && <Banner tone="danger" message={error} />}

        {newCode ? (
          <Card>
            <View style={{ gap: spacing.md }}>
              <Text variant="label" color="textSecondary">
                {t('inviteCodeTitle')}
              </Text>
              <Text
                variant="display"
                script="latin"
                selectable
                accessibilityLabel={newCode.split('').join(' ')}
              >
                {formatInviteCode(newCode)}
              </Text>
              <Text variant="bodySm" color="textSecondary">
                {t('inviteCodeHint')}
              </Text>
              <View style={{ flexDirection: 'row', gap: spacing.sm }}>
                <View style={{ flex: 1 }}>
                  <Button
                    title={t('shareCodeButton')}
                    variant="primary"
                    icon={{ ios: 'square.and.arrow.up', android: 'share', web: 'share' }}
                    onPress={handleShare}
                  />
                </View>
                <Button
                  title={copied ? t('copiedButton') : t('copyButton')}
                  variant="secondary"
                  fullWidth={false}
                  onPress={handleCopy}
                />
              </View>
            </View>
          </Card>
        ) : (
          <Button
            title={t('olderAppCreateCodeButton')}
            variant="secondary"
            loading={creating}
            loadingTitle={t('creatingInviteCode')}
            onPress={handleCreate}
          />
        )}

        {unusedCodes.length > 0 && (
          <View style={{ gap: spacing.sm }}>
            <Text variant="label" color="textSecondary">
              {t('unusedCodesLabel')}
            </Text>
            {unusedCodes.map((code) => (
              <Card key={code.id} padding="md">
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}>
                  <View style={{ flex: 1 }}>
                    <Text variant="title" script="latin">
                      {formatInviteCode(code.invite_code)}
                    </Text>
                    <Text variant="caption" color="textMuted">
                      {t('unusedCodeExpires', {
                        time: inviteCodeExpiresAt(code.created_at).toLocaleString(),
                      })}
                    </Text>
                  </View>
                  <Button
                    title={t('cancelCodeButton')}
                    accessibilityLabel={t('cancelCodeLabel', { code: code.invite_code })}
                    variant="dangerOutline"
                    size="small"
                    fullWidth={false}
                    loading={cancellingId === code.id}
                    onPress={() => handleCancel(code)}
                  />
                </View>
              </Card>
            ))}
          </View>
        )}
      </View>
    </Card>
  );
}
